import { DataSource } from 'typeorm';
import { AppError } from './errors';
import { AdminUser } from '../entities/AdminUser';
import { AdminRole } from '../entities/AdminRole';
import { AdminStoreAccess } from '../entities/AdminStoreAccess';

export const ACTION_ROLE_MAP: Record<string, { module: string; rolesAllowed: string[]; storeAccessRequired: boolean }> = {
  adminHealthWhoAmI: { module: 'health', rolesAllowed: ['superadmin', 'ops', 'viewer'], storeAccessRequired: false },
  adminHealthDbCheck: { module: 'health', rolesAllowed: ['superadmin', 'ops'], storeAccessRequired: false },
  adminHealthActionsCoverage: { module: 'health', rolesAllowed: ['superadmin', 'ops'], storeAccessRequired: false },
  adminActionsList: { module: 'health', rolesAllowed: ['superadmin', 'ops', 'viewer'], storeAccessRequired: false },
  adminMe: { module: 'account', rolesAllowed: ['superadmin', 'ops', 'viewer'], storeAccessRequired: false },
  adminEdgeSyncIngest: { module: 'edgeSync', rolesAllowed: ['edgeSync', 'admin'], storeAccessRequired: true },

  adminDineInSettingsGet: { module: 'dineIn', rolesAllowed: ['owner', 'manager'], storeAccessRequired: true },
  adminDineInSettingsUpdate: { module: 'dineIn', rolesAllowed: ['owner', 'manager'], storeAccessRequired: true },
  adminDineInTablesList: { module: 'dineIn', rolesAllowed: ['owner', 'manager', 'operations'], storeAccessRequired: true },
  adminDineInTablesGet: { module: 'dineIn', rolesAllowed: ['owner', 'manager', 'operations'], storeAccessRequired: true },
  adminDineInTablesCreate: { module: 'dineIn', rolesAllowed: ['owner', 'manager', 'operations'], storeAccessRequired: true },
  adminDineInTablesUpdate: { module: 'dineIn', rolesAllowed: ['owner', 'manager', 'operations'], storeAccessRequired: true },
  adminDineInTablesDisable: { module: 'dineIn', rolesAllowed: ['owner', 'manager', 'operations'], storeAccessRequired: true },
  adminDineInTablesGenerateQr: { module: 'dineIn', rolesAllowed: ['owner', 'manager', 'operations'], storeAccessRequired: true },
  adminDineInTablesRegenerateQr: { module: 'dineIn', rolesAllowed: ['owner', 'manager', 'operations'], storeAccessRequired: true },
  adminDineInTablesBulkGeneratePdfData: { module: 'dineIn', rolesAllowed: ['owner', 'manager', 'operations'], storeAccessRequired: true },
  adminDineInSessionsList: { module: 'dineIn', rolesAllowed: ['owner', 'manager', 'operations'], storeAccessRequired: true },
  adminDineInSessionsGet: { module: 'dineIn', rolesAllowed: ['owner', 'manager', 'operations'], storeAccessRequired: true },
  adminDineInSessionsClose: { module: 'dineIn', rolesAllowed: ['owner', 'manager', 'operations'], storeAccessRequired: true },
  adminDineInWaiterCallsList: { module: 'dineIn', rolesAllowed: ['owner', 'manager', 'operations', 'support'], storeAccessRequired: true },
  adminDineInWaiterCallsGet: { module: 'dineIn', rolesAllowed: ['owner', 'manager', 'operations', 'support'], storeAccessRequired: true },
  adminDineInWaiterCallsAcknowledge: { module: 'dineIn', rolesAllowed: ['owner', 'manager', 'operations', 'support'], storeAccessRequired: true },
  adminDineInWaiterCallsResolve: { module: 'dineIn', rolesAllowed: ['owner', 'manager', 'operations', 'support'], storeAccessRequired: true },
  adminDineInDashboardStats: { module: 'dineIn', rolesAllowed: ['owner', 'manager', 'analyst'], storeAccessRequired: true },

  adminStoresList: { module: 'stores', rolesAllowed: ['superadmin', 'ops', 'store_manager'], storeAccessRequired: false },
  adminStoresGet: { module: 'stores', rolesAllowed: ['superadmin', 'ops', 'store_manager'], storeAccessRequired: true },
  adminStoresCreate: { module: 'stores', rolesAllowed: ['superadmin', 'ops'], storeAccessRequired: false },
  adminStoresUpdate: { module: 'stores', rolesAllowed: ['superadmin', 'ops', 'store_manager'], storeAccessRequired: true },
  adminStoresDisable: { module: 'stores', rolesAllowed: ['superadmin', 'ops'], storeAccessRequired: true },
  adminStoreSettingsGet: { module: 'stores', rolesAllowed: ['superadmin', 'ops', 'store_manager'], storeAccessRequired: true },
  adminStoreSettingsUpdate: { module: 'stores', rolesAllowed: ['superadmin', 'ops', 'store_manager'], storeAccessRequired: true },

  adminCustomersList: { module: 'customers', rolesAllowed: ['superadmin', 'ops', 'support'], storeAccessRequired: false },
  adminCustomersGet: { module: 'customers', rolesAllowed: ['superadmin', 'ops', 'support'], storeAccessRequired: false },
  adminCustomersUpdate: { module: 'customers', rolesAllowed: ['superadmin', 'ops', 'support'], storeAccessRequired: false },
  adminCustomersDisable: { module: 'customers', rolesAllowed: ['superadmin', 'ops'], storeAccessRequired: false },
  adminCustomersSearch: { module: 'customers', rolesAllowed: ['superadmin', 'ops', 'support'], storeAccessRequired: false },


  adminCategoriesList: { module: 'catalog', rolesAllowed: ['superadmin', 'ops', 'catalog_manager'], storeAccessRequired: true },
  adminCategoriesGet: { module: 'catalog', rolesAllowed: ['superadmin', 'ops', 'catalog_manager'], storeAccessRequired: true },
  adminCategoriesCreate: { module: 'catalog', rolesAllowed: ['superadmin', 'ops', 'catalog_manager'], storeAccessRequired: true },
  adminCategoriesUpdate: { module: 'catalog', rolesAllowed: ['superadmin', 'ops', 'catalog_manager'], storeAccessRequired: true },
  adminCategoriesDisable: { module: 'catalog', rolesAllowed: ['superadmin', 'ops', 'catalog_manager'], storeAccessRequired: true },
  adminBannersList: { module: 'home', rolesAllowed: ['superadmin', 'ops', 'home_manager'], storeAccessRequired: true },
  adminBannersGet: { module: 'home', rolesAllowed: ['superadmin', 'ops', 'home_manager'], storeAccessRequired: true },
  adminBannersCreate: { module: 'home', rolesAllowed: ['superadmin', 'ops', 'home_manager'], storeAccessRequired: true },
  adminBannersUpdate: { module: 'home', rolesAllowed: ['superadmin', 'ops', 'home_manager'], storeAccessRequired: true },
  adminBannersDisable: { module: 'home', rolesAllowed: ['superadmin', 'ops', 'home_manager'], storeAccessRequired: true },
  adminFeaturedList: { module: 'home', rolesAllowed: ['superadmin', 'ops', 'home_manager'], storeAccessRequired: true },
  adminFeaturedSearchProducts: { module: 'products', rolesAllowed: ['superadmin', 'ops', 'product_manager'], storeAccessRequired: true },
  adminFeaturedSet: { module: 'home', rolesAllowed: ['superadmin', 'ops', 'home_manager'], storeAccessRequired: true },
  adminCatalogRebuildProductMetrics: { module: 'products', rolesAllowed: ['superadmin', 'ops', 'product_manager'], storeAccessRequired: true },
  adminProductsList: { module: 'products', rolesAllowed: ['superadmin', 'ops', 'product_manager'], storeAccessRequired: true },
  adminProductsGet: { module: 'products', rolesAllowed: ['superadmin', 'ops', 'product_manager'], storeAccessRequired: true },
  adminProductsCreate: { module: 'products', rolesAllowed: ['superadmin', 'ops', 'product_manager'], storeAccessRequired: true },
  adminProductsUpdate: { module: 'products', rolesAllowed: ['superadmin', 'ops', 'product_manager'], storeAccessRequired: true },
  adminProductsDisable: { module: 'products', rolesAllowed: ['superadmin', 'ops', 'product_manager'], storeAccessRequired: true },
  adminProductAliasesList: { module: 'products', rolesAllowed: ['superadmin', 'ops', 'product_manager', 'admin'], storeAccessRequired: true },
  adminProductAliasGet: { module: 'products', rolesAllowed: ['superadmin', 'ops', 'product_manager', 'admin'], storeAccessRequired: true },
  adminProductAliasUpsert: { module: 'products', rolesAllowed: ['superadmin', 'ops', 'product_manager', 'admin'], storeAccessRequired: true },
  adminProductAliasDelete: { module: 'products', rolesAllowed: ['superadmin', 'ops', 'product_manager', 'admin'], storeAccessRequired: true },
  adminProductImagesList: { module: 'products', rolesAllowed: ['superadmin', 'ops', 'product_manager'], storeAccessRequired: true },
  adminProductImagesAdd: { module: 'products', rolesAllowed: ['superadmin', 'ops', 'product_manager'], storeAccessRequired: true },
  adminProductImagesRemove: { module: 'products', rolesAllowed: ['superadmin', 'ops', 'product_manager'], storeAccessRequired: true },
  adminProductImagesReorder: { module: 'products', rolesAllowed: ['superadmin', 'ops', 'product_manager'], storeAccessRequired: true },
  adminProductSpecsList: { module: 'products', rolesAllowed: ['superadmin', 'ops', 'product_manager'], storeAccessRequired: true },
  adminProductSpecsCreate: { module: 'products', rolesAllowed: ['superadmin', 'ops', 'product_manager'], storeAccessRequired: true },
  adminProductSpecsUpdate: { module: 'products', rolesAllowed: ['superadmin', 'ops', 'product_manager'], storeAccessRequired: true },
  adminProductSpecsDelete: { module: 'products', rolesAllowed: ['superadmin', 'ops', 'product_manager'], storeAccessRequired: true },
  adminProductVariantsList: { module: 'products', rolesAllowed: ['superadmin', 'ops', 'product_manager'], storeAccessRequired: true },
  adminProductVariantsCreate: { module: 'products', rolesAllowed: ['superadmin', 'ops', 'product_manager'], storeAccessRequired: true },
  adminProductVariantsUpdate: { module: 'products', rolesAllowed: ['superadmin', 'ops', 'product_manager'], storeAccessRequired: true },
  adminProductVariantsDelete: { module: 'products', rolesAllowed: ['superadmin', 'ops', 'product_manager'], storeAccessRequired: true },
  adminProductVariantsBulkStockUpdate: { module: 'inventory', rolesAllowed: ['superadmin', 'ops', 'inventory_manager'], storeAccessRequired: true },
  adminInventoryAdjust: { module: 'inventory', rolesAllowed: ['superadmin', 'ops', 'inventory_manager'], storeAccessRequired: true },
  adminInventoryHistory: { module: 'inventory', rolesAllowed: ['superadmin', 'ops', 'inventory_manager'], storeAccessRequired: true },
  adminInventoryLowStockReport: { module: 'inventory', rolesAllowed: ['superadmin', 'ops', 'inventory_manager'], storeAccessRequired: true },
  adminHomeSectionsList: { module: 'home', rolesAllowed: ['superadmin', 'ops', 'home_manager'], storeAccessRequired: true },
  adminHomeSectionsGet: { module: 'home', rolesAllowed: ['superadmin', 'ops', 'home_manager'], storeAccessRequired: true },
  adminHomeSectionsCreate: { module: 'home', rolesAllowed: ['superadmin', 'ops', 'home_manager'], storeAccessRequired: true },
  adminHomeSectionsUpdate: { module: 'home', rolesAllowed: ['superadmin', 'ops', 'home_manager'], storeAccessRequired: true },
  adminHomeSectionsDisable: { module: 'home', rolesAllowed: ['superadmin', 'ops', 'home_manager'], storeAccessRequired: true },
  adminHomeSectionsReorder: { module: 'home', rolesAllowed: ['superadmin', 'ops', 'home_manager'], storeAccessRequired: true },
  adminSeoGet: { module: 'seo', rolesAllowed: ['superadmin', 'ops', 'seo_manager'], storeAccessRequired: true },
  adminSeoUpdate: { module: 'seo', rolesAllowed: ['superadmin', 'ops', 'seo_manager'], storeAccessRequired: true },
  adminLandingPagesList: { module: 'seo', rolesAllowed: ['superadmin', 'ops', 'seo_manager'], storeAccessRequired: true },
  adminLandingPagesGet: { module: 'seo', rolesAllowed: ['superadmin', 'ops', 'seo_manager'], storeAccessRequired: true },
  adminLandingPagesCreate: { module: 'seo', rolesAllowed: ['superadmin', 'ops', 'seo_manager'], storeAccessRequired: true },
  adminLandingPagesUpdate: { module: 'seo', rolesAllowed: ['superadmin', 'ops', 'seo_manager'], storeAccessRequired: true },
  adminLandingPagesPublish: { module: 'seo', rolesAllowed: ['superadmin', 'ops', 'seo_manager'], storeAccessRequired: true },
  adminLandingPagesUnpublish: { module: 'seo', rolesAllowed: ['superadmin', 'ops', 'seo_manager'], storeAccessRequired: true },
  adminLandingPagesDisable: { module: 'seo', rolesAllowed: ['superadmin', 'ops', 'seo_manager'], storeAccessRequired: true },
  adminSitemapGet: { module: 'seo', rolesAllowed: ['superadmin', 'ops', 'seo_manager'], storeAccessRequired: true },
  adminSitemapRegenerate: { module: 'seo', rolesAllowed: ['superadmin', 'ops', 'seo_manager'], storeAccessRequired: true },

  adminShippingMethodsList: { module: 'shipping', rolesAllowed: ['superadmin','ops','shipping_manager'], storeAccessRequired: true },
  adminShippingMethodsGet: { module: 'shipping', rolesAllowed: ['superadmin','ops','shipping_manager'], storeAccessRequired: true },
  adminShippingMethodsCreate: { module: 'shipping', rolesAllowed: ['superadmin','ops','shipping_manager'], storeAccessRequired: true },
  adminShippingMethodsUpdate: { module: 'shipping', rolesAllowed: ['superadmin','ops','shipping_manager'], storeAccessRequired: true },
  adminShippingMethodsDisable: { module: 'shipping', rolesAllowed: ['superadmin','ops','shipping_manager'], storeAccessRequired: true },
  adminDeliveryZonesList: { module: 'shipping', rolesAllowed: ['superadmin','ops','shipping_manager'], storeAccessRequired: true },
  adminDeliveryZonesGet: { module: 'shipping', rolesAllowed: ['superadmin','ops','shipping_manager'], storeAccessRequired: true },
  adminDeliveryZonesCreate: { module: 'shipping', rolesAllowed: ['superadmin','ops','shipping_manager'], storeAccessRequired: true },
  adminDeliveryZonesUpdate: { module: 'shipping', rolesAllowed: ['superadmin','ops','shipping_manager'], storeAccessRequired: true },
  adminDeliveryZonesDisable: { module: 'shipping', rolesAllowed: ['superadmin','ops','shipping_manager'], storeAccessRequired: true },
  adminCouponsList: { module: 'promotions', rolesAllowed: ['superadmin','ops','promotion_manager'], storeAccessRequired: true },
  adminCouponsGet: { module: 'promotions', rolesAllowed: ['superadmin','ops','promotion_manager'], storeAccessRequired: true },
  adminCouponsCreate: { module: 'promotions', rolesAllowed: ['superadmin','ops','promotion_manager'], storeAccessRequired: true },
  adminCouponsUpdate: { module: 'promotions', rolesAllowed: ['superadmin','ops','promotion_manager'], storeAccessRequired: true },
  adminCouponsDisable: { module: 'promotions', rolesAllowed: ['superadmin','ops','promotion_manager'], storeAccessRequired: true },
  adminCashbackList: { module: 'promotions', rolesAllowed: ['superadmin','ops','promotion_manager'], storeAccessRequired: true },
  adminCashbackGet: { module: 'promotions', rolesAllowed: ['superadmin','ops','promotion_manager'], storeAccessRequired: true },
  adminCashbackCreate: { module: 'promotions', rolesAllowed: ['superadmin','ops','promotion_manager'], storeAccessRequired: true },
  adminCashbackUpdate: { module: 'promotions', rolesAllowed: ['superadmin','ops','promotion_manager'], storeAccessRequired: true },
  adminCashbackDisable: { module: 'promotions', rolesAllowed: ['superadmin','ops','promotion_manager'], storeAccessRequired: true },
  adminDiscountsList: { module: 'promotions', rolesAllowed: ['superadmin','ops','promotion_manager'], storeAccessRequired: true },
  adminDiscountsGet: { module: 'promotions', rolesAllowed: ['superadmin','ops','promotion_manager'], storeAccessRequired: true },
  adminDiscountsCreate: { module: 'promotions', rolesAllowed: ['superadmin','ops','promotion_manager'], storeAccessRequired: true },
  adminDiscountsUpdate: { module: 'promotions', rolesAllowed: ['superadmin','ops','promotion_manager'], storeAccessRequired: true },
  adminDiscountsDisable: { module: 'promotions', rolesAllowed: ['superadmin','ops','promotion_manager'], storeAccessRequired: true },
  adminDiscountsPreviewAudienceCount: { module: 'promotions', rolesAllowed: ['superadmin','ops','promotion_manager'], storeAccessRequired: true },
  adminNotificationsSend: { module: 'notifications', rolesAllowed: ['superadmin','ops','notification_manager'], storeAccessRequired: false },
  adminNotificationsList: { module: 'notifications', rolesAllowed: ['superadmin','ops','notification_manager'], storeAccessRequired: false },
  adminLoyaltyGetSettings: { module: 'loyalty', rolesAllowed: ['superadmin','ops','loyalty_manager'], storeAccessRequired: true },
  adminLoyaltyUpdateSettings: { module: 'loyalty', rolesAllowed: ['superadmin','ops','loyalty_manager'], storeAccessRequired: true },
  adminLoyaltyAdjustUserPoints: { module: 'loyalty', rolesAllowed: ['superadmin','ops','loyalty_manager'], storeAccessRequired: true },
  adminLoyaltyTiersList: { module: 'loyalty', rolesAllowed: ['superadmin','ops','loyalty_manager'], storeAccessRequired: true },
  adminLoyaltyTiersCreate: { module: 'loyalty', rolesAllowed: ['superadmin','ops','loyalty_manager'], storeAccessRequired: true },
  adminLoyaltyTiersUpdate: { module: 'loyalty', rolesAllowed: ['superadmin','ops','loyalty_manager'], storeAccessRequired: true },
  adminLoyaltyTiersDisable: { module: 'loyalty', rolesAllowed: ['superadmin','ops','loyalty_manager'], storeAccessRequired: true },
  adminReportsAttributionOverview: { module: 'reportsMarketing', rolesAllowed: ['marketing','manager','admin'], storeAccessRequired: true },
  adminReportsTopCampaigns: { module: 'reportsMarketing', rolesAllowed: ['marketing','manager','admin'], storeAccessRequired: true },
  adminPostPurchaseFlowsList: { module: 'growth', rolesAllowed: ['superadmin','ops','growth_manager'], storeAccessRequired: true },
  adminPostPurchaseFlowsGet: { module: 'growth', rolesAllowed: ['superadmin','ops','growth_manager'], storeAccessRequired: true },
  adminPostPurchaseFlowsCreate: { module: 'growth', rolesAllowed: ['superadmin','ops','growth_manager'], storeAccessRequired: true },
  adminPostPurchaseFlowsUpdate: { module: 'growth', rolesAllowed: ['superadmin','ops','growth_manager'], storeAccessRequired: true },
  adminPostPurchaseFlowsDisable: { module: 'growth', rolesAllowed: ['superadmin','ops','growth_manager'], storeAccessRequired: true },
  adminPostPurchaseRunsList: { module: 'growth', rolesAllowed: ['superadmin','ops','growth_manager'], storeAccessRequired: true },
  adminOrdersList: { module: 'orders', rolesAllowed: ['superadmin','ops'], storeAccessRequired: true },
  adminOrdersGet: { module: 'orders', rolesAllowed: ['superadmin','ops'], storeAccessRequired: true },
  adminOrdersCreate: { module: 'orders', rolesAllowed: ['superadmin','ops'], storeAccessRequired: true },
  adminOrdersUpdateStatus: { module: 'orders', rolesAllowed: ['superadmin','ops'], storeAccessRequired: true },
  adminOrdersSetTracking: { module: 'orders', rolesAllowed: ['superadmin','ops'], storeAccessRequired: true },
  adminOrdersAddInternalNote: { module: 'orders', rolesAllowed: ['superadmin','ops'], storeAccessRequired: true },
  adminOrdersInvoiceUrl: { module: 'orders', rolesAllowed: ['superadmin','ops'], storeAccessRequired: true },
  adminOrdersTrackingGet: { module: 'orders', rolesAllowed: ['superadmin','ops'], storeAccessRequired: true },
  adminOrdersTrackingAddEvent: { module: 'orders', rolesAllowed: ['superadmin','ops'], storeAccessRequired: true },
  adminOrdersTrackingDeleteEvent: { module: 'orders', rolesAllowed: ['superadmin','ops'], storeAccessRequired: true },
  adminOrdersTrackingUpdateShipment: { module: 'orders', rolesAllowed: ['superadmin','ops'], storeAccessRequired: true },
  adminInsuranceList: { module: 'insurance', rolesAllowed: ['insuranceAgent','insuranceManager','admin'], storeAccessRequired: true },
  adminInsuranceGet: { module: 'insurance', rolesAllowed: ['insuranceAgent','insuranceManager','admin'], storeAccessRequired: true },
  adminInsuranceAddItem: { module: 'insurance', rolesAllowed: ['insuranceAgent','insuranceManager','admin'], storeAccessRequired: true },
  adminInsuranceUpdateItem: { module: 'insurance', rolesAllowed: ['insuranceAgent','insuranceManager','admin'], storeAccessRequired: true },
  adminInsuranceRemoveItem: { module: 'insurance', rolesAllowed: ['insuranceAgent','insuranceManager','admin'], storeAccessRequired: true },
  adminInsuranceLockQuote: { module: 'insurance', rolesAllowed: ['insuranceAgent','insuranceManager','admin'], storeAccessRequired: true },
  adminInsuranceSendQuote: { module: 'insurance', rolesAllowed: ['insuranceAgent','insuranceManager','admin'], storeAccessRequired: true },
  adminInsuranceSetShipmentTracking: { module: 'insurance', rolesAllowed: ['insuranceAgent','insuranceManager','admin'], storeAccessRequired: true },
  adminPrescriptionList: { module: 'prescriptions', rolesAllowed: ['insuranceAgent', 'insuranceManager', 'ops', 'admin'], storeAccessRequired: true },
  adminPrescriptionGet: { module: 'prescriptions', rolesAllowed: ['insuranceAgent', 'insuranceManager', 'ops', 'admin'], storeAccessRequired: true },
  adminPrescriptionMarkUnderReview: { module: 'prescriptions', rolesAllowed: ['insuranceAgent', 'insuranceManager', 'ops', 'admin'], storeAccessRequired: true },
  adminPrescriptionApprove: { module: 'prescriptions', rolesAllowed: ['insuranceAgent', 'insuranceManager', 'ops', 'admin'], storeAccessRequired: true },
  adminPrescriptionReject: { module: 'prescriptions', rolesAllowed: ['insuranceAgent', 'insuranceManager', 'ops', 'admin'], storeAccessRequired: true },
  adminPrescriptionSetItemsDraft: { module: 'prescriptions', rolesAllowed: ['insuranceAgent', 'insuranceManager', 'ops', 'admin'], storeAccessRequired: true },
  adminPrescriptionConvertToOrder: { module: 'prescriptions', rolesAllowed: ['insuranceAgent', 'insuranceManager', 'ops', 'admin'], storeAccessRequired: true },
  adminPrescriptionLinkExistingOrder: { module: 'prescriptions', rolesAllowed: ['insuranceAgent', 'insuranceManager', 'ops', 'admin'], storeAccessRequired: true },
  adminRiskRulesGet: { module: 'risk', rolesAllowed: ['superadmin','ops'], storeAccessRequired: true },
  adminRiskRulesUpdate: { module: 'risk', rolesAllowed: ['superadmin','ops'], storeAccessRequired: true },
  adminRiskFlaggedOrdersList: { module: 'risk', rolesAllowed: ['superadmin','ops'], storeAccessRequired: true },
  adminRiskFlaggedOrdersResolve: { module: 'risk', rolesAllowed: ['superadmin','ops'], storeAccessRequired: true },
  adminBranchesList: { module: 'accounting', rolesAllowed: ['superadmin','ops'], storeAccessRequired: true },
  adminBranchesCreate: { module: 'accounting', rolesAllowed: ['superadmin','ops'], storeAccessRequired: true },
  adminBranchesUpdate: { module: 'accounting', rolesAllowed: ['superadmin','ops'], storeAccessRequired: true },
  adminBranchesDisable: { module: 'accounting', rolesAllowed: ['superadmin','ops'], storeAccessRequired: true },
  adminDevicesList: { module: 'accounting', rolesAllowed: ['superadmin','ops'], storeAccessRequired: true },
  adminDevicesCreate: { module: 'accounting', rolesAllowed: ['superadmin','ops'], storeAccessRequired: true },
  adminDevicesUpdate: { module: 'accounting', rolesAllowed: ['superadmin','ops'], storeAccessRequired: true },
  adminDevicesDisable: { module: 'accounting', rolesAllowed: ['superadmin','ops'], storeAccessRequired: true },
  adminEmployeesList: { module: 'accounting', rolesAllowed: ['superadmin','ops'], storeAccessRequired: true },
  adminEmployeesCreate: { module: 'accounting', rolesAllowed: ['superadmin','ops'], storeAccessRequired: true },
  adminEmployeesUpdate: { module: 'accounting', rolesAllowed: ['superadmin','ops'], storeAccessRequired: true },
  adminEmployeesDisable: { module: 'accounting', rolesAllowed: ['superadmin','ops'], storeAccessRequired: true },
  adminDrawersList: { module: 'accounting', rolesAllowed: ['superadmin','ops'], storeAccessRequired: true },
  adminDrawersCreate: { module: 'accounting', rolesAllowed: ['superadmin','ops'], storeAccessRequired: true },
  adminDrawersUpdate: { module: 'accounting', rolesAllowed: ['superadmin','ops'], storeAccessRequired: true },
  adminDrawersDisable: { module: 'accounting', rolesAllowed: ['superadmin','ops'], storeAccessRequired: true },
  adminDrawerSessionsOpen: { module: 'accounting', rolesAllowed: ['superadmin','ops'], storeAccessRequired: true },
  adminDrawerSessionsClose: { module: 'accounting', rolesAllowed: ['superadmin','ops'], storeAccessRequired: true },
  adminDrawerSessionsList: { module: 'accounting', rolesAllowed: ['superadmin','ops','accountant','finance','admin'], storeAccessRequired: true },
  adminDrawerSessionsGet: { module: 'accounting', rolesAllowed: ['superadmin','ops','accountant','finance','admin'], storeAccessRequired: true },
  adminDrawerReconciliationsList: { module: 'accounting', rolesAllowed: ['superadmin','ops','accountant','finance','admin'], storeAccessRequired: true },
  adminAccountingKpis: { module: 'reportsAccounting', rolesAllowed: ['accountant','finance','admin'], storeAccessRequired: true },
  adminAccountingLedger: { module: 'reportsAccounting', rolesAllowed: ['accountant','finance','admin'], storeAccessRequired: true },
  adminAccountingCreateExpense: { module: 'accounting', rolesAllowed: ['superadmin','ops'], storeAccessRequired: true },
  adminAccountingCreateAdjustment: { module: 'accounting', rolesAllowed: ['superadmin','ops'], storeAccessRequired: true },
  adminAccountingCreatePOSSale: { module: 'accounting', rolesAllowed: ['superadmin','ops'], storeAccessRequired: true },
  adminChartOfAccountsList: { module: 'accounting', rolesAllowed: ['superadmin','accountant','finance','admin'], storeAccessRequired: true },
  adminChartOfAccountsCreate: { module: 'accounting', rolesAllowed: ['superadmin','accountant','finance','admin'], storeAccessRequired: true },
  adminChartOfAccountsUpdate: { module: 'accounting', rolesAllowed: ['superadmin','accountant','finance','admin'], storeAccessRequired: true },
  adminChartOfAccountsSetActive: { module: 'accounting', rolesAllowed: ['superadmin','accountant','finance','admin'], storeAccessRequired: true },
  adminJournalEntriesList: { module: 'accounting', rolesAllowed: ['superadmin','accountant','finance','admin'], storeAccessRequired: true },
  adminJournalEntriesGet: { module: 'accounting', rolesAllowed: ['superadmin','accountant','finance','admin'], storeAccessRequired: true },
  adminJournalEntriesCreate: { module: 'accounting', rolesAllowed: ['superadmin','accountant','finance','admin'], storeAccessRequired: true },
  adminJournalEntriesPost: { module: 'accounting', rolesAllowed: ['superadmin','accountant','finance','admin'], storeAccessRequired: true },
  adminJournalEntriesReverse: { module: 'accounting', rolesAllowed: ['superadmin','accountant','finance','admin'], storeAccessRequired: true },
  adminJournalEntriesRetry: { module: 'accounting', rolesAllowed: ['superadmin','accountant','finance','admin'], storeAccessRequired: true },
  adminAccountingPeriodsList: { module: 'accounting', rolesAllowed: ['superadmin','accountant','finance','admin'], storeAccessRequired: true },
  adminAccountingPeriodsCreate: { module: 'accounting', rolesAllowed: ['superadmin','accountant','finance','admin'], storeAccessRequired: true },
  adminAccountingPeriodsUpdate: { module: 'accounting', rolesAllowed: ['superadmin','accountant','finance','admin'], storeAccessRequired: true },
  adminAccountingPeriodsSetStatus: { module: 'accounting', rolesAllowed: ['superadmin','accountant','finance','admin'], storeAccessRequired: true },
  adminAccountingPeriodsOpen: { module: 'accounting', rolesAllowed: ['superadmin','accountant','finance','admin'], storeAccessRequired: true },
  adminAccountingPeriodsClose: { module: 'accounting', rolesAllowed: ['superadmin','accountant','finance','admin'], storeAccessRequired: true },
  adminPostingRulesList: { module: 'accounting', rolesAllowed: ['superadmin','accountant','finance','admin'], storeAccessRequired: true },
  adminPostingRulesCreate: { module: 'accounting', rolesAllowed: ['superadmin','accountant','finance','admin'], storeAccessRequired: true },
  adminPostingRulesUpdate: { module: 'accounting', rolesAllowed: ['superadmin','accountant','finance','admin'], storeAccessRequired: true },

  adminPosSessionsOpen: { module: 'pos', rolesAllowed: ['superadmin','ops'], storeAccessRequired: true },
  adminPosSessionsClose: { module: 'pos', rolesAllowed: ['superadmin','ops'], storeAccessRequired: true },
  adminPosSessionsList: { module: 'pos', rolesAllowed: ['superadmin','ops','viewer'], storeAccessRequired: true },
  adminPosSalesCreate: { module: 'pos', rolesAllowed: ['superadmin','ops'], storeAccessRequired: true },
  adminPosSalesGet: { module: 'pos', rolesAllowed: ['superadmin','ops','viewer'], storeAccessRequired: true },
  adminPosSalesList: { module: 'pos', rolesAllowed: ['superadmin','ops','viewer'], storeAccessRequired: true },
  adminPosReturnsCreate: { module: 'pos', rolesAllowed: ['superadmin','ops'], storeAccessRequired: true },
  adminPosReturnsGet: { module: 'pos', rolesAllowed: ['superadmin','ops','viewer'], storeAccessRequired: true },
  adminPosReturnsList: { module: 'pos', rolesAllowed: ['superadmin','ops','viewer'], storeAccessRequired: true },
  adminPosRefundsCreate: { module: 'pos', rolesAllowed: ['superadmin','ops'], storeAccessRequired: true },
  adminPosRefundsList: { module: 'pos', rolesAllowed: ['superadmin','ops','viewer'], storeAccessRequired: true },
  reportsOverview: { module: 'reportsBasic', rolesAllowed: ['manager','admin','analyst'], storeAccessRequired: true },
  reportsTopProducts: { module: 'reportsBasic', rolesAllowed: ['manager','admin','analyst'], storeAccessRequired: true },
  reportsOrdersByStatus: { module: 'reportsBasic', rolesAllowed: ['manager','admin','analyst'], storeAccessRequired: true },
  reportsInventorySummary: { module: 'reportsBasic', rolesAllowed: ['manager','admin','analyst'], storeAccessRequired: true },
  reportsCustomersSummary: { module: 'reportsBasic', rolesAllowed: ['manager','admin','analyst'], storeAccessRequired: true },
  reportsReturnsSummary: { module: 'reportsBasic', rolesAllowed: ['manager','admin','analyst'], storeAccessRequired: true },
  reportsLoyaltySummary: { module: 'reportsBasic', rolesAllowed: ['manager','admin','analyst'], storeAccessRequired: true },
  reportsCashbackSummary: { module: 'reportsBasic', rolesAllowed: ['manager','admin','analyst'], storeAccessRequired: true },
  adminReturnsList: { module: 'returns', rolesAllowed: ['superadmin','ops'], storeAccessRequired: true },
  adminReturnsGet: { module: 'returns', rolesAllowed: ['superadmin','ops'], storeAccessRequired: true },
  adminReturnsApprove: { module: 'returns', rolesAllowed: ['superadmin','ops'], storeAccessRequired: true },
  adminReturnsReject: { module: 'returns', rolesAllowed: ['superadmin','ops'], storeAccessRequired: true },
  adminReturnsRefundPartial: { module: 'returns', rolesAllowed: ['superadmin','ops'], storeAccessRequired: true },
  adminReturnsRefundFull: { module: 'returns', rolesAllowed: ['superadmin','ops'], storeAccessRequired: true },
  adminReturnsUpdateStatus: { module: 'returns', rolesAllowed: ['superadmin','ops'], storeAccessRequired: true },
  adminInventoryImportCreateBatch: { module: 'inventoryImport', rolesAllowed: ['inventoryManager','admin'], storeAccessRequired: true },
  adminInventoryImportPreview: { module: 'inventoryImport', rolesAllowed: ['inventoryManager','admin'], storeAccessRequired: true },
  adminInventoryImportGetUnmappedPrefixes: { module: 'inventoryImport', rolesAllowed: ['inventoryManager','admin'], storeAccessRequired: true },
  adminInventoryImportResolvePrefixes: { module: 'inventoryImport', rolesAllowed: ['inventoryManager','admin'], storeAccessRequired: true },
  adminInventoryImportApply: { module: 'inventoryImport', rolesAllowed: ['inventoryManager','admin'], storeAccessRequired: true },
  adminInventoryImportGet: { module: 'inventoryImport', rolesAllowed: ['inventoryManager','admin'], storeAccessRequired: true },
  adminPriceImportCreateSession: { module: 'pricingImport', rolesAllowed: ['inventoryManager', 'product_manager', 'admin'], storeAccessRequired: true },
  adminPriceImportUploadSheet: { module: 'pricingImport', rolesAllowed: ['inventoryManager', 'product_manager', 'admin'], storeAccessRequired: true },
  adminPriceImportParsePreview: { module: 'pricingImport', rolesAllowed: ['inventoryManager', 'product_manager', 'admin'], storeAccessRequired: true },
  adminPriceImportResolveMatch: { module: 'pricingImport', rolesAllowed: ['inventoryManager', 'product_manager', 'admin'], storeAccessRequired: true },
  adminPriceImportApply: { module: 'pricingImport', rolesAllowed: ['inventoryManager', 'product_manager', 'admin'], storeAccessRequired: true },
  adminPriceImportListMappings: { module: 'pricingImport', rolesAllowed: ['inventoryManager', 'product_manager', 'admin'], storeAccessRequired: true },
  adminPriceImportUpsertMapping: { module: 'pricingImport', rolesAllowed: ['inventoryManager', 'product_manager', 'admin'], storeAccessRequired: true },
  adminPriceImportDeleteMapping: { module: 'pricingImport', rolesAllowed: ['inventoryManager', 'product_manager', 'admin'], storeAccessRequired: true },
  adminSuppliersList: { module: 'procurement', rolesAllowed: ['superadmin', 'ops', 'inventoryManager', 'admin'], storeAccessRequired: true },
  adminSuppliersCreate: { module: 'procurement', rolesAllowed: ['superadmin', 'ops', 'inventoryManager', 'admin'], storeAccessRequired: true },
  adminSuppliersUpdate: { module: 'procurement', rolesAllowed: ['superadmin', 'ops', 'inventoryManager', 'admin'], storeAccessRequired: true },
  adminSuppliersDisable: { module: 'procurement', rolesAllowed: ['superadmin', 'ops', 'inventoryManager', 'admin'], storeAccessRequired: true },
  adminWarehousesList: { module: 'procurement', rolesAllowed: ['superadmin', 'ops', 'inventoryManager', 'admin'], storeAccessRequired: true },
  adminWarehousesCreate: { module: 'procurement', rolesAllowed: ['superadmin', 'ops', 'inventoryManager', 'admin'], storeAccessRequired: true },
  adminWarehousesUpdate: { module: 'procurement', rolesAllowed: ['superadmin', 'ops', 'inventoryManager', 'admin'], storeAccessRequired: true },
  adminWarehousesDisable: { module: 'procurement', rolesAllowed: ['superadmin', 'ops', 'inventoryManager', 'admin'], storeAccessRequired: true },
  adminPurchaseOrdersList: { module: 'procurement', rolesAllowed: ['superadmin', 'ops', 'inventoryManager', 'admin'], storeAccessRequired: true },
  adminPurchaseOrdersGet: { module: 'procurement', rolesAllowed: ['superadmin', 'ops', 'inventoryManager', 'admin'], storeAccessRequired: true },
  adminPurchaseOrdersCreate: { module: 'procurement', rolesAllowed: ['superadmin', 'ops', 'inventoryManager', 'admin'], storeAccessRequired: true },
  adminPurchaseOrdersUpdate: { module: 'procurement', rolesAllowed: ['superadmin', 'ops', 'inventoryManager', 'admin'], storeAccessRequired: true },
  adminPurchaseOrdersSubmit: { module: 'procurement', rolesAllowed: ['superadmin', 'ops', 'inventoryManager', 'admin'], storeAccessRequired: true },
  adminPurchaseOrdersApprove: { module: 'procurement', rolesAllowed: ['superadmin', 'ops', 'inventoryManager', 'admin'], storeAccessRequired: true },
  adminPurchaseOrdersCancel: { module: 'procurement', rolesAllowed: ['superadmin', 'ops', 'inventoryManager', 'admin'], storeAccessRequired: true },
  adminPurchaseOrdersReceive: { module: 'procurement', rolesAllowed: ['superadmin', 'ops', 'inventoryManager', 'admin'], storeAccessRequired: true },
  adminGoodsReceiptsList: { module: 'procurement', rolesAllowed: ['superadmin', 'ops', 'inventoryManager', 'admin'], storeAccessRequired: true },
  adminGoodsReceiptsGet: { module: 'procurement', rolesAllowed: ['superadmin', 'ops', 'inventoryManager', 'admin'], storeAccessRequired: true },
  adminGoodsReceiptsCreate: { module: 'procurement', rolesAllowed: ['superadmin', 'ops', 'inventoryManager', 'admin'], storeAccessRequired: true },
  adminStockMovementsList: { module: 'procurement', rolesAllowed: ['superadmin', 'ops', 'inventoryManager', 'admin'], storeAccessRequired: true },
  adminInventoryBatchesList: { module: 'procurement', rolesAllowed: ['superadmin', 'ops', 'inventoryManager', 'admin'], storeAccessRequired: true },
  adminInventoryBatchesUpdate: { module: 'procurement', rolesAllowed: ['superadmin', 'ops', 'inventoryManager', 'admin'], storeAccessRequired: true },
  adminMediaCreateUploadSpec: { module: 'media', rolesAllowed: ['superadmin', 'ops', 'content_manager'], storeAccessRequired: false },
  adminMediaFinalizeUpload: { module: 'media', rolesAllowed: ['superadmin', 'ops', 'content_manager'], storeAccessRequired: false },
};

export async function rbacCheckOrThrow(db: DataSource, adminUid: string, action: string, storeId?: string) {
  const policy = ACTION_ROLE_MAP[action];
  if (!policy) throw new AppError('RBAC_POLICY_MISSING', `RBAC policy missing for action ${action}`);

  const user = await db.getRepository(AdminUser).findOne({ where: { uid: adminUid } });
  if (!user || user.status !== 'active') {
    throw new AppError('FORBIDDEN', 'Admin user is not active');
  }

  const roles = await db.getRepository(AdminRole).find({ where: { adminUid } });
  const roleSet = new Set(roles.map((r: AdminRole) => r.role));
  if (!policy.rolesAllowed.some((role) => roleSet.has(role))) {
    throw new AppError('FORBIDDEN', 'Missing required admin role');
  }
  if (policy.storeAccessRequired) {
    if (!storeId) throw new AppError('STORE_ACCESS_REQUIRED', 'storeId is required for this action');
    const access = await db.getRepository(AdminStoreAccess).findOne({ where: { adminUid, storeId } });
    if (!access) throw new AppError('STORE_ACCESS_REQUIRED', 'Missing store access');
  }
}
