import Joi from 'joi';
import { onCall } from 'firebase-functions/v2/https';
import { getDataSource } from '../../db/data-source';
import { CashbackCampaignEntity } from '../../db/entities/CashbackCampaignEntity';
import { writeAudit } from '../../lib/audit';
import { verifyAdminRole, verifyFirebaseUser, verifyStoreAccess } from '../../lib/auth';
import { mapError, notFound } from '../../lib/errors';
import { uuidSchema, validatePayload } from '../../lib/validators';

const ensureAdmin = async (uid: string, storeId: string) => { await verifyAdminRole(uid, ['SUPER_ADMIN','STORE_ADMIN','MARKETING']); await verifyStoreAccess(uid, storeId); };
const schema = Joi.object({ name: Joi.string().required(), type: Joi.string().valid('threshold','products','categories').required(), rewardType: Joi.string().valid('fixed','percent').required(), value: Joi.number().positive().required(), minSubtotal: Joi.number().min(0).allow(null), maxReward: Joi.number().min(0).allow(null), targetJson: Joi.object().unknown(true).allow(null), startAt: Joi.date().allow(null), endAt: Joi.date().allow(null), usageLimitTotal: Joi.number().integer().min(0).allow(null), usageLimitPerUser: Joi.number().integer().min(0).allow(null), isActive: Joi.boolean().default(true) });

export const adminCashbackList = onCall(async (r)=>{ try{ const p=validatePayload(Joi.object({storeId:uuidSchema.required()}),r.data); const uid=verifyFirebaseUser(r); await ensureAdmin(uid,p.storeId); const items=await (await getDataSource()).getRepository(CashbackCampaignEntity).find({where:{storeId:p.storeId},order:{createdAt:'DESC'}}); return {items}; }catch(e){mapError(e);} });
export const adminCashbackGet = onCall(async (r)=>{ try{ const p=validatePayload(Joi.object({storeId:uuidSchema.required(),campaignId:uuidSchema.required()}),r.data); const uid=verifyFirebaseUser(r); await ensureAdmin(uid,p.storeId); const row=await (await getDataSource()).getRepository(CashbackCampaignEntity).findOne({where:{id:p.campaignId,storeId:p.storeId}}); if(!row) notFound('Campaign not found.'); return {campaign:row}; }catch(e){mapError(e);} });
export const adminCashbackCreate = onCall(async (r)=>{ try{ const p=validatePayload(Joi.object({storeId:uuidSchema.required(),payload:schema.required()}),r.data); const uid=verifyFirebaseUser(r); await ensureAdmin(uid,p.storeId); const repo=(await getDataSource()).getRepository(CashbackCampaignEntity); const row=await repo.save(repo.create({...p.payload,storeId:p.storeId,value:Number(p.payload.value).toFixed(2),minSubtotal:p.payload.minSubtotal==null?null:Number(p.payload.minSubtotal).toFixed(2),maxReward:p.payload.maxReward==null?null:Number(p.payload.maxReward).toFixed(2)})); await writeAudit({actorType:'admin',actorUid:uid,action:'admin.cashback.create',targetType:'cashback_campaign',targetId:row.id,storeId:p.storeId}); return {campaign:row}; }catch(e){mapError(e);} });
export const adminCashbackUpdate = onCall(async (r)=>{ try{ const p=validatePayload(Joi.object({storeId:uuidSchema.required(),campaignId:uuidSchema.required(),payload:schema.fork(['name','type','rewardType','value'],(s)=>s.optional()).min(1).required()}),r.data); const uid=verifyFirebaseUser(r); await ensureAdmin(uid,p.storeId); const repo=(await getDataSource()).getRepository(CashbackCampaignEntity); const row=await repo.findOne({where:{id:p.campaignId,storeId:p.storeId}}); if(!row) notFound('Campaign not found.'); Object.assign(row,p.payload); if((p.payload as any).value!==undefined) row.value=Number((p.payload as any).value).toFixed(2); if((p.payload as any).minSubtotal!==undefined) row.minSubtotal=(p.payload as any).minSubtotal==null?null:Number((p.payload as any).minSubtotal).toFixed(2); if((p.payload as any).maxReward!==undefined) row.maxReward=(p.payload as any).maxReward==null?null:Number((p.payload as any).maxReward).toFixed(2); const saved=await repo.save(row); await writeAudit({actorType:'admin',actorUid:uid,action:'admin.cashback.update',targetType:'cashback_campaign',targetId:saved.id,storeId:p.storeId}); return {campaign:saved}; }catch(e){mapError(e);} });
export const adminCashbackDisable = onCall(async (r)=>{ try{ const p=validatePayload(Joi.object({storeId:uuidSchema.required(),campaignId:uuidSchema.required()}),r.data); const uid=verifyFirebaseUser(r); await ensureAdmin(uid,p.storeId); const repo=(await getDataSource()).getRepository(CashbackCampaignEntity); const row=await repo.findOne({where:{id:p.campaignId,storeId:p.storeId}}); if(!row) notFound('Campaign not found.'); row.isActive=false; await repo.save(row); await writeAudit({actorType:'admin',actorUid:uid,action:'admin.cashback.disable',targetType:'cashback_campaign',targetId:row.id,storeId:p.storeId}); return {success:true}; }catch(e){mapError(e);} });
