import Joi from 'joi';
import { onCall } from 'firebase-functions/v2/https';
import { getDataSource } from '../../db/data-source';
import { DiscountCampaignEntity } from '../../db/entities/DiscountCampaignEntity';
import { writeAudit } from '../../lib/audit';
import { verifyAdminRole, verifyFirebaseUser, verifyStoreAccess } from '../../lib/auth';
import { previewAudienceCount } from '../../lib/discounts';
import { mapError, notFound } from '../../lib/errors';
import { uuidSchema, validatePayload } from '../../lib/validators';

const ensureAdmin = async (uid: string, storeId: string) => { await verifyAdminRole(uid, ['SUPER_ADMIN','STORE_ADMIN','MARKETING']); await verifyStoreAccess(uid, storeId); };
const schema = Joi.object({ name:Joi.string().required(), isActive:Joi.boolean().default(true), priority:Joi.number().integer().default(0), startAt:Joi.date().allow(null), endAt:Joi.date().allow(null), audienceJson:Joi.object().unknown(true).required(), appliesToJson:Joi.object().unknown(true).required(), discountType:Joi.string().valid('percent','fixed').required(), value:Joi.number().positive().required(), maxDiscount:Joi.number().positive().allow(null), minSubtotal:Joi.number().min(0).allow(null) });

export const adminDiscountsList = onCall(async (r)=>{ try{ const p=validatePayload(Joi.object({storeId:uuidSchema.required()}),r.data); const uid=verifyFirebaseUser(r); await ensureAdmin(uid,p.storeId); const items=await (await getDataSource()).getRepository(DiscountCampaignEntity).find({where:{storeId:p.storeId},order:{priority:'DESC',createdAt:'DESC'}}); return {items}; }catch(e){mapError(e);} });
export const adminDiscountsGet = onCall(async (r)=>{ try{ const p=validatePayload(Joi.object({storeId:uuidSchema.required(),campaignId:uuidSchema.required()}),r.data); const uid=verifyFirebaseUser(r); await ensureAdmin(uid,p.storeId); const row=await (await getDataSource()).getRepository(DiscountCampaignEntity).findOne({where:{id:p.campaignId,storeId:p.storeId}}); if(!row) notFound('Discount campaign not found.'); return {campaign:row}; }catch(e){mapError(e);} });
export const adminDiscountsCreate = onCall(async (r)=>{ try{ const p=validatePayload(Joi.object({storeId:uuidSchema.required(),payload:schema.required()}),r.data); const uid=verifyFirebaseUser(r); await ensureAdmin(uid,p.storeId); const repo=(await getDataSource()).getRepository(DiscountCampaignEntity); const row=await repo.save(repo.create({...p.payload,storeId:p.storeId,value:Number(p.payload.value).toFixed(2),maxDiscount:p.payload.maxDiscount==null?null:Number(p.payload.maxDiscount).toFixed(2),minSubtotal:p.payload.minSubtotal==null?null:Number(p.payload.minSubtotal).toFixed(2)})); await writeAudit({actorType:'admin',actorUid:uid,action:'admin.discount.create',targetType:'discount_campaign',targetId:row.id,storeId:p.storeId}); return {campaign:row}; }catch(e){mapError(e);} });
export const adminDiscountsUpdate = onCall(async (r)=>{ try{ const p=validatePayload(Joi.object({storeId:uuidSchema.required(),campaignId:uuidSchema.required(),payload:schema.fork(['name','audienceJson','appliesToJson','discountType','value'],(s)=>s.optional()).min(1).required()}),r.data); const uid=verifyFirebaseUser(r); await ensureAdmin(uid,p.storeId); const repo=(await getDataSource()).getRepository(DiscountCampaignEntity); const row=await repo.findOne({where:{id:p.campaignId,storeId:p.storeId}}); if(!row) notFound('Discount campaign not found.'); Object.assign(row,p.payload); if((p.payload as any).value!==undefined) row.value=Number((p.payload as any).value).toFixed(2); if((p.payload as any).maxDiscount!==undefined) row.maxDiscount=(p.payload as any).maxDiscount==null?null:Number((p.payload as any).maxDiscount).toFixed(2); if((p.payload as any).minSubtotal!==undefined) row.minSubtotal=(p.payload as any).minSubtotal==null?null:Number((p.payload as any).minSubtotal).toFixed(2); const saved=await repo.save(row); await writeAudit({actorType:'admin',actorUid:uid,action:'admin.discount.update',targetType:'discount_campaign',targetId:saved.id,storeId:p.storeId}); return {campaign:saved}; }catch(e){mapError(e);} });
export const adminDiscountsDisable = onCall(async (r)=>{ try{ const p=validatePayload(Joi.object({storeId:uuidSchema.required(),campaignId:uuidSchema.required()}),r.data); const uid=verifyFirebaseUser(r); await ensureAdmin(uid,p.storeId); const repo=(await getDataSource()).getRepository(DiscountCampaignEntity); const row=await repo.findOne({where:{id:p.campaignId,storeId:p.storeId}}); if(!row) notFound('Discount campaign not found.'); row.isActive=false; await repo.save(row); await writeAudit({actorType:'admin',actorUid:uid,action:'admin.discount.disable',targetType:'discount_campaign',targetId:row.id,storeId:p.storeId}); return {success:true}; }catch(e){mapError(e);} });
export const adminDiscountsPreviewAudienceCount = onCall(async (r)=>{ try{ const p=validatePayload(Joi.object({storeId:uuidSchema.required(),audienceJson:Joi.object().unknown(true).required()}),r.data); const uid=verifyFirebaseUser(r); await ensureAdmin(uid,p.storeId); const count=await previewAudienceCount(p.storeId,p.audienceJson); return {count}; }catch(e){mapError(e);} });
