import Joi from 'joi';
import { onCall } from 'firebase-functions/v2/https';
import { getDataSource } from '../../db/data-source';
import { HomeSectionEntity } from '../../db/entities/HomeSectionEntity';
import { writeAudit } from '../../lib/audit';
import { verifyAdminRole, verifyFirebaseUser, verifyStoreAccess } from '../../lib/auth';
import { mapError, notFound } from '../../lib/errors';
import { uuidSchema, validatePayload } from '../../lib/validators';

const ensureAdmin = async (uid: string, storeId: string) => {
  await verifyAdminRole(uid, ['SUPER_ADMIN', 'STORE_ADMIN', 'MARKETING']);
  await verifyStoreAccess(uid, storeId);
};

const payloadSchema = Joi.object({ type: Joi.string().valid('banners','categories_row','products_carousel','products_grid','single_banner').required(), title: Joi.string().allow(null, ''), sortOrder: Joi.number().integer().min(0).default(0), isActive: Joi.boolean().default(true), configJson: Joi.object().unknown(true).required() });

export const adminHomeSectionsList = onCall(async (request) => { try { const payload = validatePayload(Joi.object({ storeId: uuidSchema.required() }), request.data); const uid = verifyFirebaseUser(request); await ensureAdmin(uid, payload.storeId); const items = await (await getDataSource()).getRepository(HomeSectionEntity).find({ where: { storeId: payload.storeId }, order: { sortOrder: 'ASC' } }); return { items }; } catch (e) { mapError(e); } });
export const adminHomeSectionsGet = onCall(async (request) => { try { const payload = validatePayload(Joi.object({ storeId: uuidSchema.required(), sectionId: uuidSchema.required() }), request.data); const uid = verifyFirebaseUser(request); await ensureAdmin(uid, payload.storeId); const row = await (await getDataSource()).getRepository(HomeSectionEntity).findOne({ where: { id: payload.sectionId, storeId: payload.storeId } }); if (!row) notFound('Section not found.'); return { section: row }; } catch (e) { mapError(e); } });
export const adminHomeSectionsCreate = onCall(async (request) => { try { const payload = validatePayload(Joi.object({ storeId: uuidSchema.required(), payload: payloadSchema.required() }), request.data); const uid = verifyFirebaseUser(request); await ensureAdmin(uid, payload.storeId); const repo = (await getDataSource()).getRepository(HomeSectionEntity); const row = await repo.save(repo.create({ ...payload.payload, storeId: payload.storeId, title: payload.payload.title || null })); await writeAudit({ actorType: 'admin', actorUid: uid, action: 'admin.home_section.create', targetType: 'home_section', targetId: row.id, storeId: payload.storeId }); return { section: row }; } catch (e) { mapError(e); } });
export const adminHomeSectionsUpdate = onCall(async (request) => { try { const payload = validatePayload(Joi.object({ storeId: uuidSchema.required(), sectionId: uuidSchema.required(), payload: payloadSchema.fork(['type','configJson'], (s)=>s.optional()).min(1).required() }), request.data); const uid = verifyFirebaseUser(request); await ensureAdmin(uid, payload.storeId); const repo = (await getDataSource()).getRepository(HomeSectionEntity); const row = await repo.findOne({ where: { id: payload.sectionId, storeId: payload.storeId } }); if (!row) notFound('Section not found.'); Object.assign(row, payload.payload); if ((payload.payload as any).title !== undefined) row.title = (payload.payload as any).title || null; const saved = await repo.save(row); await writeAudit({ actorType: 'admin', actorUid: uid, action: 'admin.home_section.update', targetType: 'home_section', targetId: saved.id, storeId: payload.storeId }); return { section: saved }; } catch (e) { mapError(e); } });
export const adminHomeSectionsDisable = onCall(async (request) => { try { const payload = validatePayload(Joi.object({ storeId: uuidSchema.required(), sectionId: uuidSchema.required() }), request.data); const uid = verifyFirebaseUser(request); await ensureAdmin(uid, payload.storeId); const repo = (await getDataSource()).getRepository(HomeSectionEntity); const row = await repo.findOne({ where: { id: payload.sectionId, storeId: payload.storeId } }); if (!row) notFound('Section not found.'); row.isActive = false; await repo.save(row); await writeAudit({ actorType: 'admin', actorUid: uid, action: 'admin.home_section.disable', targetType: 'home_section', targetId: row.id, storeId: payload.storeId }); return { success: true }; } catch (e) { mapError(e); } });
export const adminHomeSectionsReorder = onCall(async (request) => { try { const payload = validatePayload(Joi.object({ storeId: uuidSchema.required(), items: Joi.array().items(Joi.object({ sectionId: uuidSchema.required(), sortOrder: Joi.number().integer().min(0).required() })).min(1).required() }), request.data); const uid = verifyFirebaseUser(request); await ensureAdmin(uid, payload.storeId); const repo = (await getDataSource()).getRepository(HomeSectionEntity); for (const item of payload.items) { await repo.update({ id: item.sectionId, storeId: payload.storeId }, { sortOrder: item.sortOrder }); } await writeAudit({ actorType: 'admin', actorUid: uid, action: 'admin.home_section.reorder', targetType: 'home_section', targetId: payload.storeId, storeId: payload.storeId }); return { success: true }; } catch (e) { mapError(e); } });
