export const STABLE_ERROR_CODES = {
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  FORBIDDEN: 'FORBIDDEN',
  STORE_ACCESS_REQUIRED: 'STORE_ACCESS_REQUIRED',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  QUERY_SORT_INVALID: 'QUERY_SORT_INVALID',
  QUERY_FILTERS_INVALID: 'QUERY_FILTERS_INVALID',
  QUERY_SEARCH_INVALID: 'QUERY_SEARCH_INVALID',
  QUERY_PAGINATION_INVALID: 'QUERY_PAGINATION_INVALID',
  QUERY_RANGE_INVALID: 'QUERY_RANGE_INVALID',
  QUERY_GROUP_BY_INVALID: 'QUERY_GROUP_BY_INVALID',
  QUERY_COLUMNS_INVALID: 'QUERY_COLUMNS_INVALID',
  UNSUPPORTED_ACTION: 'UNSUPPORTED_ACTION',
  NOT_FOUND: 'NOT_FOUND',
  INVALID_STATE: 'INVALID_STATE',
  PUBLIC_STORE_ID_REQUIRED: 'PUBLIC_STORE_ID_REQUIRED',
  PUBLIC_STORE_ID_INVALID: 'PUBLIC_STORE_ID_INVALID',
  INTERNAL: 'INTERNAL',
} as const;

export type StableErrorCode = (typeof STABLE_ERROR_CODES)[keyof typeof STABLE_ERROR_CODES];
