export const STABLE_ERROR_CODES = {
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  FORBIDDEN: 'FORBIDDEN',
  STORE_ACCESS_REQUIRED: 'STORE_ACCESS_REQUIRED',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  PUBLIC_STORE_ID_REQUIRED: 'PUBLIC_STORE_ID_REQUIRED',
  PUBLIC_STORE_ID_INVALID: 'PUBLIC_STORE_ID_INVALID',
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL: 'INTERNAL',
} as const;

export type StableErrorCode = (typeof STABLE_ERROR_CODES)[keyof typeof STABLE_ERROR_CODES];
