import { ActionHandler } from '../core/protocol';
import {
  deliveryAcceptOrder,
  deliveryArrivedDropoff,
  deliveryArrivedPickup,
  deliveryDelivered,
  deliveryFailedDelivery,
  deliveryGatewayHealth,
  deliveryGetActiveTrip,
  deliveryGetDashboard,
  deliveryGetOrderDetails,
  deliveryGetProfile,
  deliveryHeartbeat,
  deliveryListAssignedOrders,
  deliveryListHistory,
  deliveryPickedUp,
  deliveryRejectOrder,
  deliverySetOnTheWay,
  deliverySetPresence,
  deliveryUpdateLocation,
  deliveryWhoAmI,
} from '../actions/delivery/deliveryActions';

export const DELIVERY_ACTION_REGISTRY: Record<string, ActionHandler> = {
  deliveryGatewayHealth: deliveryGatewayHealth as ActionHandler,
  deliveryWhoAmI: deliveryWhoAmI as ActionHandler,
  deliverySetPresence: deliverySetPresence as ActionHandler,
  deliveryHeartbeat: deliveryHeartbeat as ActionHandler,
  deliveryUpdateLocation: deliveryUpdateLocation as ActionHandler,
  deliveryListAssignedOrders: deliveryListAssignedOrders as ActionHandler,
  deliveryGetActiveTrip: deliveryGetActiveTrip as ActionHandler,
  deliveryGetOrderDetails: deliveryGetOrderDetails as ActionHandler,
  deliveryAcceptOrder: deliveryAcceptOrder as ActionHandler,
  deliveryRejectOrder: deliveryRejectOrder as ActionHandler,
  deliveryArrivedPickup: deliveryArrivedPickup as ActionHandler,
  deliveryPickedUp: deliveryPickedUp as ActionHandler,
  deliverySetOnTheWay: deliverySetOnTheWay as ActionHandler,
  deliveryArrivedDropoff: deliveryArrivedDropoff as ActionHandler,
  deliveryDelivered: deliveryDelivered as ActionHandler,
  deliveryFailedDelivery: deliveryFailedDelivery as ActionHandler,
  deliveryListHistory: deliveryListHistory as ActionHandler,
  deliveryGetDashboard: deliveryGetDashboard as ActionHandler,
  deliveryGetProfile: deliveryGetProfile as ActionHandler,
};
