export const ADMIN_ACTIONS_SOT = [
  'adminHealthWhoAmI','adminHealthDbCheck','adminHealthActionsCoverage','adminActionsList','adminMe',
  'adminStoresList','adminStoresGet','adminStoresCreate','adminStoresUpdate','adminStoresDisable','adminStoreSettingsGet','adminStoreSettingsUpdate',
  'adminCustomersList','adminCustomersGet','adminCustomersUpdate','adminCustomersDisable','adminCustomersSearch',
  'adminCategoriesList','adminCategoriesGet','adminCategoriesCreate','adminCategoriesUpdate','adminCategoriesDisable',
  'adminBannersList','adminBannersGet','adminBannersCreate','adminBannersUpdate','adminBannersDisable',
  'adminFeaturedList','adminFeaturedSearchProducts','adminFeaturedSet',
  'adminProductsList','adminProductsGet','adminProductsCreate','adminProductsUpdate','adminProductsDisable',
  'adminProductImagesList','adminProductImagesAdd','adminProductImagesRemove','adminProductImagesReorder',
  'adminProductSpecsList','adminProductSpecsCreate','adminProductSpecsUpdate','adminProductSpecsDelete',
  'adminProductVariantsList','adminProductVariantsCreate','adminProductVariantsUpdate','adminProductVariantsDelete','adminProductVariantsBulkStockUpdate',
  'adminInventoryAdjust','adminInventoryHistory','adminInventoryLowStockReport',
  'adminHomeSectionsList','adminHomeSectionsGet','adminHomeSectionsCreate','adminHomeSectionsUpdate','adminHomeSectionsDisable','adminHomeSectionsReorder',
  'adminSeoGet','adminSeoUpdate',
  'adminLandingPagesList','adminLandingPagesGet','adminLandingPagesCreate','adminLandingPagesUpdate','adminLandingPagesPublish','adminLandingPagesUnpublish','adminLandingPagesDisable',
  'adminSitemapRegenerate',
  'adminShippingMethodsList','adminShippingMethodsGet','adminShippingMethodsCreate','adminShippingMethodsUpdate','adminShippingMethodsDisable',
  'adminDeliveryZonesList','adminDeliveryZonesGet','adminDeliveryZonesCreate','adminDeliveryZonesUpdate','adminDeliveryZonesDisable',
  'adminCouponsList','adminCouponsGet','adminCouponsCreate','adminCouponsUpdate','adminCouponsDisable',
  'adminCashbackList','adminCashbackGet','adminCashbackCreate','adminCashbackUpdate','adminCashbackDisable',
  'adminDiscountsList','adminDiscountsGet','adminDiscountsCreate','adminDiscountsUpdate','adminDiscountsDisable','adminDiscountsPreviewAudienceCount',
  'adminNotificationsSend','adminNotificationsList',
  'adminLoyaltyGetSettings','adminLoyaltyUpdateSettings','adminLoyaltyAdjustUserPoints',
  'adminLoyaltyTiersList','adminLoyaltyTiersCreate','adminLoyaltyTiersUpdate','adminLoyaltyTiersDisable',
  'adminReportsAttributionOverview','adminReportsTopCampaigns',
  'adminPostPurchaseFlowsList','adminPostPurchaseFlowsGet','adminPostPurchaseFlowsCreate','adminPostPurchaseFlowsUpdate','adminPostPurchaseFlowsDisable','adminPostPurchaseRunsList',
  'adminMediaCreateUploadSpec','adminMediaFinalizeUpload',
] as const;
