export const DELIVERY_ACTIONS_SOT = [
  'deliveryGatewayHealth',
  'deliveryWhoAmI',
  'deliverySetPresence',
  'deliveryHeartbeat',
  'deliveryUpdateLocation',
  'deliveryListAssignedOrders',
  'deliveryGetActiveTrip',
  'deliveryGetOrderDetails',
  'deliveryAcceptOrder',
  'deliveryRejectOrder',
  'deliveryArrivedPickup',
  'deliveryPickedUp',
  'deliverySetOnTheWay',
  'deliveryArrivedDropoff',
  'deliveryDelivered',
  'deliveryFailedDelivery',
  'deliveryListHistory',
  'deliveryGetDashboard',
  'deliveryGetProfile',
] as const;
