import { MigrationInterface, QueryRunner } from 'typeorm';

export class Phase4CommerceMarketing1725000000000 implements MigrationInterface {
  name = 'Phase4CommerceMarketing1725000000000';
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS shipping_methods (id char(36) PRIMARY KEY, storeId varchar(64) NOT NULL, name varchar(80) NOT NULL, basePriceCents bigint NOT NULL, status varchar(24) NOT NULL DEFAULT 'active', createdAt datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, updatedAt datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, KEY idx_shipping_methods_store_status (storeId,status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS governorates (id char(36) PRIMARY KEY, name varchar(80) NOT NULL, status varchar(24) NOT NULL DEFAULT 'active') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS delivery_zones (id char(36) PRIMARY KEY, storeId varchar(64) NOT NULL, governorateId char(36) NOT NULL, name varchar(120) NOT NULL, lat decimal(10,7) NOT NULL, lng decimal(10,7) NOT NULL, priceCents bigint NOT NULL, status varchar(24) NOT NULL DEFAULT 'active', KEY idx_delivery_zones_store_status (storeId,status), KEY idx_delivery_zones_gov (governorateId)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS carts (id char(36) PRIMARY KEY, uid varchar(128) NOT NULL, storeId varchar(64) NOT NULL, couponCode varchar(64) NULL, createdAt datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, updatedAt datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, UNIQUE KEY uq_carts_uid_store (uid,storeId)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS cart_items (id char(36) PRIMARY KEY, cartId char(36) NOT NULL, productId char(36) NOT NULL, variantId char(36) NULL, qty int NOT NULL, unitPriceCents bigint NOT NULL, KEY idx_cart_items_cart (cartId)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS coupons (id char(36) PRIMARY KEY, storeId varchar(64) NOT NULL, code varchar(64) NOT NULL, discountType varchar(24) NOT NULL, discountValue bigint NOT NULL, startsAt datetime NULL, endsAt datetime NULL, perUserLimit int NOT NULL DEFAULT 0, status varchar(24) NOT NULL DEFAULT 'active', UNIQUE KEY uq_coupons_store_code (storeId,code), KEY idx_coupons_store_status (storeId,status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS targeted_discounts (id char(36) PRIMARY KEY, storeId varchar(64) NOT NULL, name varchar(120) NOT NULL, rules json NOT NULL, status varchar(24) NOT NULL DEFAULT 'active', KEY idx_targeted_discounts_store_status (storeId,status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS cashback_offers (id char(36) PRIMARY KEY, storeId varchar(64) NOT NULL, name varchar(120) NOT NULL, percent int NOT NULL, rules json NULL, status varchar(24) NOT NULL DEFAULT 'active', KEY idx_cashback_offers_store_status (storeId,status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS wallet_accounts (uid varchar(128) PRIMARY KEY, balanceCents bigint NOT NULL DEFAULT 0, updatedAt datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS wallet_transactions (id char(36) PRIMARY KEY, uid varchar(128) NOT NULL, amountCents bigint NOT NULL, type varchar(40) NOT NULL, note varchar(255) NULL, createdAt datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, KEY idx_wallet_transactions_uid_created (uid,createdAt)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS loyalty_settings (storeId varchar(64) PRIMARY KEY, pointsPerCurrencyUnit int NOT NULL DEFAULT 1, redeemStepPoints int NOT NULL DEFAULT 100, redeemStepValueCents bigint NOT NULL DEFAULT 100) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS loyalty_tiers (id char(36) PRIMARY KEY, storeId varchar(64) NOT NULL, name varchar(80) NOT NULL, minPoints int NOT NULL, status varchar(24) NOT NULL DEFAULT 'active', KEY idx_loyalty_tiers_store_status (storeId,status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS loyalty_transactions (id char(36) PRIMARY KEY, uid varchar(128) NOT NULL, storeId varchar(64) NOT NULL, pointsDelta int NOT NULL, type varchar(40) NOT NULL, createdAt datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, KEY idx_loyalty_transactions_uid_store_created (uid,storeId,createdAt)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS notification_tokens (id char(36) PRIMARY KEY, uid varchar(128) NOT NULL, token varchar(255) NOT NULL, platform varchar(40) NULL, createdAt datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY uq_notification_tokens_uid_token (uid,token)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS notifications (id char(36) PRIMARY KEY, uid varchar(128) NOT NULL, title varchar(160) NOT NULL, body varchar(500) NOT NULL, isRead tinyint(1) NOT NULL DEFAULT 0, createdAt datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, KEY idx_notifications_uid_read_created (uid,isRead,createdAt)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS marketing_attribution_events (id char(36) PRIMARY KEY, uid varchar(128) NOT NULL, storeId varchar(64) NULL, source varchar(120) NULL, campaign varchar(120) NULL, medium varchar(120) NULL, term varchar(120) NULL, content varchar(120) NULL, dedupeKey varchar(80) NULL, createdAt datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY uq_marketing_event_dedupe (uid,dedupeKey), KEY idx_marketing_store_source_created (storeId,source,createdAt)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS alerts_prefs (uid varchar(128) PRIMARY KEY, backInStock tinyint(1) NOT NULL DEFAULT 1, priceDrop tinyint(1) NOT NULL DEFAULT 1, updatedAt datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS alerts_subscriptions (id char(36) PRIMARY KEY, uid varchar(128) NOT NULL, productId char(36) NOT NULL, type varchar(40) NOT NULL, createdAt datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY uq_alert_subs_uid_product_type (uid,productId,type)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS post_purchase_flows (id char(36) PRIMARY KEY, storeId varchar(64) NOT NULL, name varchar(120) NOT NULL, config json NOT NULL, status varchar(24) NOT NULL DEFAULT 'active', KEY idx_post_purchase_flows_store_status (storeId,status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS post_purchase_runs (id char(36) PRIMARY KEY, flowId char(36) NOT NULL, uid varchar(128) NOT NULL, status varchar(24) NOT NULL, createdAt datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, KEY idx_post_purchase_runs_flow_created (flowId,createdAt)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS support_tickets (id char(36) PRIMARY KEY, uid varchar(128) NOT NULL, storeId varchar(64) NULL, subject varchar(160) NOT NULL, status varchar(24) NOT NULL DEFAULT 'open', createdAt datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, updatedAt datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, KEY idx_support_tickets_uid_status (uid,status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS support_messages (id char(36) PRIMARY KEY, ticketId char(36) NOT NULL, senderUid varchar(128) NOT NULL, message varchar(1000) NOT NULL, mediaAssetId char(36) NULL, createdAt datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, KEY idx_support_messages_ticket_created (ticketId,createdAt)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS user_settings (uid varchar(128) PRIMARY KEY, config json NULL, updatedAt datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
    await queryRunner.query(`CREATE TABLE IF NOT EXISTS legal_docs (id char(36) PRIMARY KEY, storeId varchar(64) NOT NULL, docType varchar(40) NOT NULL, version varchar(32) NOT NULL, content text NOT NULL, status varchar(24) NOT NULL DEFAULT 'active', createdAt datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, updatedAt datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, KEY idx_legal_docs_store_type_status (storeId,docType,status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
  }
  public async down(queryRunner: QueryRunner): Promise<void> {
    const tables=['legal_docs','user_settings','support_messages','support_tickets','post_purchase_runs','post_purchase_flows','alerts_subscriptions','alerts_prefs','marketing_attribution_events','notifications','notification_tokens','loyalty_transactions','loyalty_tiers','loyalty_settings','wallet_transactions','wallet_accounts','cashback_offers','targeted_discounts','coupons','cart_items','carts','delivery_zones','governorates','shipping_methods'];
    for(const t of tables) await queryRunner.query(`DROP TABLE IF EXISTS ${t}`);
  }
}
