import { MigrationInterface, QueryRunner } from 'typeorm';

export class Phase5OrdersInsuranceAccounting1726000000000 implements MigrationInterface {
  name = 'Phase5OrdersInsuranceAccounting1726000000000';
  public async up(queryRunner: QueryRunner): Promise<void> {
    const q = async (sql:string)=>queryRunner.query(sql);
    await q(`CREATE TABLE IF NOT EXISTS orders (id char(36) PRIMARY KEY, storeId varchar(64), uid varchar(128), channel varchar(24), status varchar(24), subtotalCents bigint, discountCents bigint, shippingCents bigint, taxCents bigint, totalCents bigint, paymentStatus varchar(24), riskStatus varchar(24), createdAt datetime DEFAULT CURRENT_TIMESTAMP, KEY idx_orders_store_status_created (storeId,status,createdAt), KEY idx_orders_uid_created (uid,createdAt)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
    await q(`CREATE TABLE IF NOT EXISTS order_items (id char(36) PRIMARY KEY, orderId char(36), productId char(36), variantId char(36) NULL, nameSnapshot varchar(180), priceCents bigint, qty int, KEY idx_order_items_order (orderId)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
    await q(`CREATE TABLE IF NOT EXISTS order_status_events (id char(36) PRIMARY KEY, orderId char(36), status varchar(24), note varchar(500) NULL, createdByUid varchar(128), createdAt datetime DEFAULT CURRENT_TIMESTAMP, KEY idx_order_status_events_order_created (orderId,createdAt)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
    await q(`CREATE TABLE IF NOT EXISTS shipments (id char(36) PRIMARY KEY, orderId char(36), carrier varchar(80) NULL, trackingNumber varchar(120) NULL, status varchar(24), updatedAt datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, UNIQUE KEY uq_shipments_order (orderId)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
    await q(`CREATE TABLE IF NOT EXISTS tracking_events (id char(36) PRIMARY KEY, shipmentId char(36), message varchar(255), location varchar(120) NULL, createdAt datetime DEFAULT CURRENT_TIMESTAMP, KEY idx_tracking_events_shipment_created (shipmentId,createdAt)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
    await q(`CREATE TABLE IF NOT EXISTS payment_sessions (id char(36) PRIMARY KEY, orderId char(36), provider varchar(40), providerSessionId varchar(120), status varchar(24), createdAt datetime DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY uq_payment_provider_session (provider,providerSessionId), KEY idx_payment_order_created (orderId,createdAt)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
    await q(`CREATE TABLE IF NOT EXISTS store_payment_settings (storeId varchar(64) PRIMARY KEY, provider varchar(40), config json) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
    await q(`CREATE TABLE IF NOT EXISTS insurance_orders (id char(36) PRIMARY KEY, storeId varchar(64), uid varchar(128), status varchar(24), quoteLocked tinyint(1) DEFAULT 0, deliveryCentsX2Applied tinyint(1) DEFAULT 0, createdAt datetime DEFAULT CURRENT_TIMESTAMP, KEY idx_insurance_orders_store_status (storeId,status), KEY idx_insurance_orders_uid_created (uid,createdAt)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
    await q(`CREATE TABLE IF NOT EXISTS insurance_files (id char(36) PRIMARY KEY, insuranceOrderId char(36), type varchar(20), mediaAssetId char(36), KEY idx_insurance_files_order_type (insuranceOrderId,type)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
    await q(`CREATE TABLE IF NOT EXISTS insurance_items (id char(36) PRIMARY KEY, insuranceOrderId char(36), name varchar(180), qty int, clientContributionCents bigint, companyContributionCents bigint, KEY idx_insurance_items_order (insuranceOrderId)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
    await q(`CREATE TABLE IF NOT EXISTS insurance_status_events (id char(36) PRIMARY KEY, insuranceOrderId char(36), status varchar(24), note varchar(500) NULL, createdByUid varchar(128), createdAt datetime DEFAULT CURRENT_TIMESTAMP, KEY idx_insurance_status_order_created (insuranceOrderId,createdAt)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
    await q(`CREATE TABLE IF NOT EXISTS risk_rules (storeId varchar(64) PRIMARY KEY, config json, updatedAt datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
    await q(`CREATE TABLE IF NOT EXISTS risk_flags (id char(36) PRIMARY KEY, orderId char(36), status varchar(24), reason varchar(300), resolvedByUid varchar(128) NULL, resolvedAt datetime NULL, KEY idx_risk_flags_status (status), KEY idx_risk_flags_order (orderId)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
    await q(`CREATE TABLE IF NOT EXISTS branches (id char(36) PRIMARY KEY, storeId varchar(64), name varchar(120), status varchar(24), KEY idx_branches_store_status (storeId,status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
    await q(`CREATE TABLE IF NOT EXISTS devices (id char(36) PRIMARY KEY, storeId varchar(64), branchId char(36) NULL, name varchar(120), status varchar(24), KEY idx_devices_store_status (storeId,status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
    await q(`CREATE TABLE IF NOT EXISTS employees (id char(36) PRIMARY KEY, storeId varchar(64), uid varchar(128), role varchar(80), status varchar(24), KEY idx_employees_store_status (storeId,status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
    await q(`CREATE TABLE IF NOT EXISTS drawers (id char(36) PRIMARY KEY, storeId varchar(64), branchId char(36) NULL, name varchar(80), status varchar(24), KEY idx_drawers_store_status (storeId,status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
    await q(`CREATE TABLE IF NOT EXISTS drawer_sessions (id char(36) PRIMARY KEY, drawerId char(36), openedByUid varchar(128), openedAt datetime, closedByUid varchar(128) NULL, closedAt datetime NULL, openingBalanceCents bigint, closingBalanceCents bigint NULL, createdAt datetime DEFAULT CURRENT_TIMESTAMP, KEY idx_drawer_sessions_drawer_opened (drawerId,openedAt)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
    await q(`CREATE TABLE IF NOT EXISTS ledger_entries (id char(36) PRIMARY KEY, storeId varchar(64), amountCents bigint, type varchar(40), channel varchar(24), branchId char(36) NULL, deviceId char(36) NULL, employeeId char(36) NULL, drawerSessionId char(36) NULL, refType varchar(40), refId varchar(64), createdAt datetime DEFAULT CURRENT_TIMESTAMP, KEY idx_ledger_store_created (storeId,createdAt), KEY idx_ledger_ref (refType,refId)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
    await q(`CREATE TABLE IF NOT EXISTS returns (id char(36) PRIMARY KEY, storeId varchar(64), orderId char(36), uid varchar(128), status varchar(24), requestedAt datetime DEFAULT CURRENT_TIMESTAMP, approvedAt datetime NULL, rejectedAt datetime NULL, KEY idx_returns_store_status (storeId,status), KEY idx_returns_order (orderId)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
    await q(`CREATE TABLE IF NOT EXISTS return_items (id char(36) PRIMARY KEY, returnId char(36), orderItemId char(36), qty int, KEY idx_return_items_return (returnId)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
    await q(`CREATE TABLE IF NOT EXISTS refunds (id char(36) PRIMARY KEY, returnId char(36), amountCents bigint, method varchar(24), status varchar(24), createdAt datetime DEFAULT CURRENT_TIMESTAMP, KEY idx_refunds_return_created (returnId,createdAt)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
  }
  public async down(queryRunner: QueryRunner): Promise<void> { const t=['refunds','return_items','returns','ledger_entries','drawer_sessions','drawers','employees','devices','branches','risk_flags','risk_rules','insurance_status_events','insurance_items','insurance_files','insurance_orders','store_payment_settings','payment_sessions','tracking_events','shipments','order_status_events','order_items','orders']; for (const x of t) await queryRunner.query(`DROP TABLE IF EXISTS ${x}`); }
}
